// Code generated by protoc-gen-grpc v4.0.0. DO NOT EDIT.
// package: com.svc
// file: service/product.proto

import * as grpc from 'grpc';
import * as service_product_pb from '../service/product_pb';
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';
import * as kitchen_product_pb from '../kitchen/product_pb';

interface IProductServiceService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
  get: IProductServiceService_IGet;
  watch: IProductServiceService_IWatch;
  upload: IProductServiceService_IUpload;
  chat: IProductServiceService_IChat;
  getKitchen: IProductServiceService_IGetKitchen;
}

interface IProductServiceService_IGet extends grpc.MethodDefinition<service_product_pb.GetReq, service_product_pb.Item> {
  path: '/com.svc.ProductService/Get'
  requestStream: false
  responseStream: false
  requestSerialize: grpc.serialize<service_product_pb.GetReq>;
  requestDeserialize: grpc.deserialize<service_product_pb.GetReq>;
  responseSerialize: grpc.serialize<service_product_pb.Item>;
  responseDeserialize: grpc.deserialize<service_product_pb.Item>;
}

interface IProductServiceService_IWatch extends grpc.MethodDefinition<service_product_pb.GetReq, service_product_pb.Item> {
  path: '/com.svc.ProductService/Watch'
  requestStream: false
  responseStream: true
  requestSerialize: grpc.serialize<service_product_pb.GetReq>;
  requestDeserialize: grpc.deserialize<service_product_pb.GetReq>;
  responseSerialize: grpc.serialize<service_product_pb.Item>;
  responseDeserialize: grpc.deserialize<service_product_pb.Item>;
}

interface IProductServiceService_IUpload extends grpc.MethodDefinition<service_product_pb.GetReq, service_product_pb.Item> {
  path: '/com.svc.ProductService/Upload'
  requestStream: true
  responseStream: false
  requestSerialize: grpc.serialize<service_product_pb.GetReq>;
  requestDeserialize: grpc.deserialize<service_product_pb.GetReq>;
  responseSerialize: grpc.serialize<service_product_pb.Item>;
  responseDeserialize: grpc.deserialize<service_product_pb.Item>;
}

interface IProductServiceService_IChat extends grpc.MethodDefinition<service_product_pb.GetReq, service_product_pb.Item> {
  path: '/com.svc.ProductService/Chat'
  requestStream: true
  responseStream: true
  requestSerialize: grpc.serialize<service_product_pb.GetReq>;
  requestDeserialize: grpc.deserialize<service_product_pb.GetReq>;
  responseSerialize: grpc.serialize<service_product_pb.Item>;
  responseDeserialize: grpc.deserialize<service_product_pb.Item>;
}

interface IProductServiceService_IGetKitchen extends grpc.MethodDefinition<service_product_pb.GetReq, kitchen_product_pb.Product> {
  path: '/com.svc.ProductService/GetKitchen'
  requestStream: false
  responseStream: false
  requestSerialize: grpc.serialize<service_product_pb.GetReq>;
  requestDeserialize: grpc.deserialize<service_product_pb.GetReq>;
  responseSerialize: grpc.serialize<kitchen_product_pb.Product>;
  responseDeserialize: grpc.deserialize<kitchen_product_pb.Product>;
}

export const ProductServiceService: IProductServiceService;
export interface IProductServiceServer extends grpc.UntypedServiceImplementation {
  get: grpc.handleUnaryCall<service_product_pb.GetReq, service_product_pb.Item>;
  watch: grpc.handleServerStreamingCall<service_product_pb.GetReq, service_product_pb.Item>;
  upload: grpc.handleClientStreamingCall<service_product_pb.GetReq, service_product_pb.Item>;
  chat: grpc.handleBidiStreamingCall<service_product_pb.GetReq, service_product_pb.Item>;
  getKitchen: grpc.handleUnaryCall<service_product_pb.GetReq, kitchen_product_pb.Product>;
}

export interface IProductServiceClient {
  get(request: service_product_pb.GetReq, callback: (error: grpc.ServiceError | null, response: service_product_pb.Item) => void): grpc.ClientUnaryCall;
  get(request: service_product_pb.GetReq, metadata: grpc.Metadata, callback: (error: grpc.ServiceError | null, response: service_product_pb.Item) => void): grpc.ClientUnaryCall;
  get(request: service_product_pb.GetReq, metadata: grpc.Metadata, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: service_product_pb.Item) => void): grpc.ClientUnaryCall;
  watch(request: service_product_pb.GetReq, options?: Partial<grpc.CallOptions>): grpc.ClientReadableStream<service_product_pb.Item>;
  watch(request: service_product_pb.GetReq, metadata?: grpc.Metadata, options?: Partial<grpc.CallOptions>): grpc.ClientReadableStream<service_product_pb.Item>;
  upload(callback: (error: grpc.ServiceError | null, response: service_product_pb.Item) => void): grpc.ClientWritableStream<service_product_pb.GetReq>;
  upload(metadata: grpc.Metadata, callback: (error: grpc.ServiceError | null, response: service_product_pb.Item) => void): grpc.ClientWritableStream<service_product_pb.GetReq>;
  upload(options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: service_product_pb.Item) => void): grpc.ClientWritableStream<service_product_pb.GetReq>;
  upload(metadata: grpc.Metadata, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: service_product_pb.Item) => void): grpc.ClientWritableStream<service_product_pb.GetReq>;
  chat(): grpc.ClientDuplexStream<service_product_pb.GetReq, service_product_pb.Item>;
  chat(options: Partial<grpc.CallOptions>): grpc.ClientDuplexStream<service_product_pb.GetReq, service_product_pb.Item>;
  chat(metadata: grpc.Metadata, options?: Partial<grpc.CallOptions>): grpc.ClientDuplexStream<service_product_pb.GetReq, service_product_pb.Item>;
  getKitchen(request: service_product_pb.GetReq, callback: (error: grpc.ServiceError | null, response: kitchen_product_pb.Product) => void): grpc.ClientUnaryCall;
  getKitchen(request: service_product_pb.GetReq, metadata: grpc.Metadata, callback: (error: grpc.ServiceError | null, response: kitchen_product_pb.Product) => void): grpc.ClientUnaryCall;
  getKitchen(request: service_product_pb.GetReq, metadata: grpc.Metadata, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: kitchen_product_pb.Product) => void): grpc.ClientUnaryCall;
}

export class ProductServiceClient extends grpc.Client implements IProductServiceClient {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: Partial<grpc.ClientOptions>);
  public get(request: service_product_pb.GetReq, callback: (error: grpc.ServiceError | null, response: service_product_pb.Item) => void): grpc.ClientUnaryCall;
  public get(request: service_product_pb.GetReq, metadata: grpc.Metadata, callback: (error: grpc.ServiceError | null, response: service_product_pb.Item) => void): grpc.ClientUnaryCall;
  public get(request: service_product_pb.GetReq, metadata: grpc.Metadata, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: service_product_pb.Item) => void): grpc.ClientUnaryCall;
  public watch(request: service_product_pb.GetReq, options?: Partial<grpc.CallOptions>): grpc.ClientReadableStream<service_product_pb.Item>;
  public watch(request: service_product_pb.GetReq, metadata?: grpc.Metadata, options?: Partial<grpc.CallOptions>): grpc.ClientReadableStream<service_product_pb.Item>;
  public upload(callback: (error: grpc.ServiceError | null, response: service_product_pb.Item) => void): grpc.ClientWritableStream<service_product_pb.GetReq>;
  public upload(metadata: grpc.Metadata, callback: (error: grpc.ServiceError | null, response: service_product_pb.Item) => void): grpc.ClientWritableStream<service_product_pb.GetReq>;
  public upload(options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: service_product_pb.Item) => void): grpc.ClientWritableStream<service_product_pb.GetReq>;
  public upload(metadata: grpc.Metadata, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: service_product_pb.Item) => void): grpc.ClientWritableStream<service_product_pb.GetReq>;
  public chat(): grpc.ClientDuplexStream<service_product_pb.GetReq, service_product_pb.Item>;
  public chat(options?: Partial<grpc.CallOptions>): grpc.ClientDuplexStream<service_product_pb.GetReq, service_product_pb.Item>;
  public chat(metadata?: grpc.Metadata, options?: Partial<grpc.CallOptions>): grpc.ClientDuplexStream<service_product_pb.GetReq, service_product_pb.Item>;
  public getKitchen(request: service_product_pb.GetReq, callback: (error: grpc.ServiceError | null, response: kitchen_product_pb.Product) => void): grpc.ClientUnaryCall;
  public getKitchen(request: service_product_pb.GetReq, metadata: grpc.Metadata, callback: (error: grpc.ServiceError | null, response: kitchen_product_pb.Product) => void): grpc.ClientUnaryCall;
  public getKitchen(request: service_product_pb.GetReq, metadata: grpc.Metadata, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: kitchen_product_pb.Product) => void): grpc.ClientUnaryCall;
}

