'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const {FileDescriptorMSG} = require('../../build/lib/descriptor/FileDescriptorMSG');
const {FileDescriptorGRPC} = require('../../build/lib/descriptor/FileDescriptorGRPC');
const {EntryMap} = require('../../build/lib/EntryMap');
const {
    kitchenSinkFile,
    serviceFile,
    externalTypesFile,
    noPackageFile,
    proto2File,
    proto3OptionalFile,
} = require('../helpers/fixtures');
const {fileDescriptor} = require('../helpers/proto-builders');

const GOLDEN_DIR = path.join(__dirname, '..', 'golden');
const TOOL_VERSION = require('../../package.json').version;

function versionHeader() {
    return `// Code generated by protoc-gen-grpc v${TOOL_VERSION}. DO NOT EDIT.`;
}

function entryMapFor(...files) {
    const entryMap = new EntryMap();
    files.forEach(fd => entryMap.parseFileDescriptor(fd));
    return entryMap;
}

function readGolden(name) {
    return fs.readFileSync(path.join(GOLDEN_DIR, name), 'utf8');
}

test('FileDescriptorMSG kitchen-sink output matches the golden baseline', () => {
    const kitchen = kitchenSinkFile();
    const all = entryMapFor(kitchen, serviceFile(), externalTypesFile(), proto2File(), proto3OptionalFile());
    assert.equal(FileDescriptorMSG.print(kitchen, all), readGolden('kitchen-product_pb.d.ts'));
});

test('FileDescriptorMSG service output matches the golden baseline', () => {
    const svc = serviceFile();
    const all = entryMapFor(kitchenSinkFile(), svc, externalTypesFile(), proto2File(), proto3OptionalFile());
    assert.equal(FileDescriptorMSG.print(svc, all), readGolden('service-product_pb.d.ts'));
});

test('FileDescriptorMSG proto2 output matches the golden baseline', () => {
    const proto2 = proto2File();
    const all = entryMapFor(kitchenSinkFile(), serviceFile(), externalTypesFile(), proto2, proto3OptionalFile());
    assert.equal(FileDescriptorMSG.print(proto2, all), readGolden('legacy-old_pb.d.ts'));
});

test('FileDescriptorMSG no-package output matches the golden baseline', () => {
    const noPkg = noPackageFile();
    const all = entryMapFor(noPkg);
    assert.equal(FileDescriptorMSG.print(noPkg, all), readGolden('nopkg-plain_pb.d.ts'));
});

test('FileDescriptorMSG proto3-optional output matches the golden baseline', () => {
    const optional = proto3OptionalFile();
    const all = entryMapFor(kitchenSinkFile(), serviceFile(), externalTypesFile(), proto2File(), optional);
    assert.equal(FileDescriptorMSG.print(optional, all), readGolden('modern-optional_pb.d.ts'));
});

test('well-known dependencies import from google-protobuf module', () => {
    const kitchen = kitchenSinkFile();
    const all = entryMapFor(kitchen, externalTypesFile());
    const output = FileDescriptorMSG.print(kitchen, all);
    assert.match(output, /import \* as google_protobuf_timestamp_pb from 'google-protobuf\/google\/protobuf\/timestamp_pb';/);
});

test('relative dependencies import with path to root', () => {
    const kitchen = kitchenSinkFile();
    const all = entryMapFor(kitchen, externalTypesFile());
    const output = FileDescriptorMSG.print(kitchen, all);
    assert.match(output, /import \* as other_types_pb from '\.\.\/other\/types_pb';/);
});

test('annotations dependency is filtered in message files too', () => {
    const svc = serviceFile();
    const all = entryMapFor(svc);
    const output = FileDescriptorMSG.print(svc, all);
    assert.equal(output.includes('annotations'), false);
});

test('empty file renders only header and jspb import', () => {
    const fd = fileDescriptor({name: 'empty.proto', pkg: 'com.e', syntax: 'proto3'});
    const output = FileDescriptorMSG.print(fd, new EntryMap());
    assert.equal(output, `${versionHeader()}\n// package: com.e\n// file: empty.proto\n\nimport * as jspb from 'google-protobuf';\n\n`);
});

test('generated files carry the tool version header', () => {
    const fd = fileDescriptor({name: 'v.proto', pkg: 'com.v', syntax: 'proto3'});
    const output = FileDescriptorMSG.print(fd, new EntryMap());
    assert.equal(output.split('\n')[0], versionHeader());
    const svc = serviceFile();
    const grpcOutput = FileDescriptorGRPC.print(svc, entryMapFor(kitchenSinkFile(), svc, externalTypesFile()));
    assert.equal(grpcOutput.split('\n')[0], versionHeader());
});
